@echo off
python gurobi_worst_case_dis_MNIST6layers_64.py 
python gurobi_worst_case_dis_MNIST6layers_128.py 
python gurobi_worst_case_dis_MNIST6layers_256.py 
python gurobi_worst_case_dis_MNIST6layers_512.py 
pause